//!/usr/bin/env groovy

// Only one build running at a time, stop prior build if new build starts
def buildNumber = BUILD_NUMBER as int; if (buildNumber > 1) milestone(buildNumber - 1); milestone(buildNumber) // Thanks to jglick

properties([
    buildDiscarder(logRotator(numToKeepStr: '15')),
    disableResume(),
    durabilityHint('PERFORMANCE_OPTIMIZED'),
    pipelineTriggers([cron('H H/8 * * *')]), // Run once every 8 hours (three times a day)
])

def categorizedLabels = [:]

// Labels currently used on trusted.ci.jenkins.io (2026-02)
// - core-taglibs-report-generator: docker&&linux
// - crawler: maven-17
// - javadoc: linux
// - jenkins.io: docker&&linux, updatecenter
// - purge-fastly-for-security-advisory: agent-1
// - reindex_maven: linux
// - repository-permissions-updater: maven-25
// - update-center-sync-recent-releases: updatecenter
// - update_center: updatecenter
// - docker controller & agents: linux, windows-2019, windows-2022, windows-2025

categorizedLabels['Maven and JDK'] = ['maven-17', 'maven-25']
categorizedLabels['Docker platforms'] = ['docker', 'linux', 'windows-2019', 'windows-2022', 'windows-2025']
categorizedLabels['Permanent agent'] = ['agent-1', 'updatecenter']

// Generate a parallel step for each label
def generateParallelSteps(categorizedLabels) {
    def parallelNodes = [:]
    categorizedLabels.each { categoryName, labels ->
        labels.each { unboundLabel ->
            def label = unboundLabel
            def stageName = "${label} / ${categoryName}"
            parallelNodes[stageName] = {
                stage(stageName) {
                    node(label) {
                        withEnv(["NODE_LABEL=${label}"]) {
                            checkout scm
                            if (isUnix()) {
                                sh 'bash ./checks.sh "${NODE_LABEL}"'
                            } else {
                                pwsh 'Get-ChildItem env:' || echo 'gci env failed'
                                pwsh 'pwsh ./checks.ps1 -Label $env:NODE_LABEL' || echo 'failure'
                            }
                        }
                    }
                }
            }
        }
    }
    return parallelNodes
}

timeout(unit: 'MINUTES', time: 29) {
    parallel generateParallelSteps(categorizedLabels)
}
