//!/usr/bin/env groovy

properties([
    buildDiscarder(logRotator(numToKeepStr: '15')),
    disableResume(),
    durabilityHint('PERFORMANCE_OPTIMIZED'),
    pipelineTriggers([cron('H H/8 * * *')]), // Run once every 8 hours (three times a day)
])

def categorizedLabels = [:]

categorizedLabels['ephemeral-agents'] = ['linux-amd64', 'linux-arm64', 'linux-arm64-nonspot']
categorizedLabels['kubernetes-agents'] = ['linux', 'jnlp-linux-amd64', 'jnlp-linux-arm64']

def clusters = ['publick8s', 'privatek8s', 'privatek8s-sponsored', 'cijioagents2', 'infracijioagents1']

// Generate a parallel step for each label
def generateParallelSteps(categorizedLabels, clusters) {
    def parallelNodes = [:]
    categorizedLabels.each { categoryName, labels ->
        labels.each { unboundLabel ->
            def label = unboundLabel
            def stageName = "${label} / ${categoryName}"
            parallelNodes[stageName] = {
                stage(stageName) {
                    node(label) {
                        withEnv(["NODE_LABEL=${label}"]) {
                            checkout scm
                            if (isUnix()) {
                                sh 'bash ./checks.sh "${NODE_LABEL}"'
                            } else {
                                pwsh 'pwsh ./checks.ps1 -Label "${env:NODE_LABEL}"'
                            }
                        }
                    }
                }
            }
        }
    }
    clusters.each { clusterName -> 
        parallelNodes[clusterName] = {
            def stageName = "${clusterName} access"
            stage(stageName) {
                node('jnlp-linux-arm64') {
                    withCredentials([file(credentialsId: "kubeconfig-${clusterName}", variable: 'KUBECONFIG')]) {
                        sh 'kubectl cluster-info'
                        sh 'kubectl get ns'
                    }
                }
            }
        }
    }
    return parallelNodes
}

timeout(unit: 'MINUTES', time: 29) {
    parallel generateParallelSteps(categorizedLabels, clusters)
}

node('jnlp-linux-arm64') {
    publishBuildStatusReport()
}
