//!/usr/bin/env groovy

properties([
    buildDiscarder(logRotator(numToKeepStr: '15')),
    disableResume(),
    durabilityHint('PERFORMANCE_OPTIMIZED'),
    pipelineTriggers([cron('H H/8 * * *')]), // Run once every 8 hours (three times a day)
])

def categorizedLabels = [:]

// Labels currently used on cert.ci.jenkins.io (2026-02-11, see https://github.com/jenkins-infra/helpdesk/issues/4955#issuecomment-3883361394)
// - linux-jdk-17
// - linux-jdk-21
// - linux-jdk-25
// - windows-jdk-17
// - windows-jdk-21
// - windows-jdk-25
// - linux
// - windows


categorizedLabels['Maven and JDK'] = ['linux-jdk-17', 'linux-jdk-21', 'linux-jdk-25', 'windows-jdk-17', 'windows-jdk-21', 'windows-jdk-25']
categorizedLabels['Others'] = ['linux', 'windows']

// Generate a parallel step for each label
def generateParallelSteps(categorizedLabels) {
    def parallelNodes = [:]
    categorizedLabels.each { categoryName, labels ->
        labels.each { unboundLabel ->
            def label = unboundLabel
            def stageName = "${label} / ${categoryName}"
            parallelNodes[stageName] = {
                stage(stageName) {
                    node(label) {
                        withEnv(["NODE_LABEL=${label}"]) {
                            checkout scm
                            if (isUnix()) {
                                sh 'bash ./checks.sh "${NODE_LABEL}"'
                            } else {
                                pwsh 'pwsh ./checks.ps1 -Label "${env:NODE_LABEL}"'
                            }
                        }
                    }
                }
            }
        }
    }
    return parallelNodes
}

timeout(unit: 'MINUTES', time: 29) {
    parallel generateParallelSteps(categorizedLabels)
}
