parallel "linux": {
  stage('Test default "linux" agent label with tools') {
    node('linux') {
      sh 'java -version'
      sh 'mvn -v'
      
      /** TODO: uncomment when adding JDK25
      String jdk25 = tool name: "jdk-25", type: 'jdk'
      withEnv(["PATH+JDK=${jdk25}/bin", "JAVA_HOME=${jdk25}"]) {
        sh 'mvn -v'
      }
      **/
      
      String jdk21 = tool name: "jdk21", type: 'jdk'
      withEnv(["PATH+JDK=${jdk21}/bin", "JAVA_HOME=${jdk21}"]) {
        sh 'mvn -v'
      }

      String jdk17 = tool name: "jdk17", type: 'jdk'
      withEnv(["PATH+JDK=${jdk17}/bin", "JAVA_HOME=${jdk17}"]) {
        sh 'mvn -v'
      }

      String jdk11 = tool name: "jdk11", type: 'jdk'
      withEnv(["PATH+JDK=${jdk11}/bin", "JAVA_HOME=${jdk11}"]) {
        sh 'mvn -v'
      }
    
      String jdk8 = tool name: "jdk8", type: 'jdk'
      withEnv(["PATH+JDK=${jdk8}/bin", "JAVA_HOME=${jdk8}"]) {
          sh 'mvn -v'
      }
    }
  }
},
"windows": {
  stage('Test default "windows" agent label with tools') {
    node('windows') {
      bat 'java -version'
      bat 'mvn -v'
      
      /** TODO: uncomment when adding JDK25
      String jdk25 = tool name: "jdk-25", type: 'jdk'
      withEnv(["PATH+JDK=${jdk25}/bin", "JAVA_HOME=${jdk25}"]) {
        bat 'mvn -v'
      }
      **/
      
      String jdk21 = tool name: "jdk21", type: 'jdk'
      withEnv(["PATH+JDK=${jdk21}/bin", "JAVA_HOME=${jdk21}"]) {
        bat 'mvn -v'
      }

      String jdk17 = tool name: "jdk17", type: 'jdk'
      withEnv(["PATH+JDK=${jdk17}/bin", "JAVA_HOME=${jdk17}"]) {
        bat 'mvn -v'
      }

      String jdk11 = tool name: "jdk11", type: 'jdk'
      withEnv(["PATH+JDK=${jdk11}/bin", "JAVA_HOME=${jdk11}"]) {
        bat 'mvn -v'
      }
    
      String jdk8 = tool name: "jdk8", type: 'jdk'
      withEnv(["PATH+JDK=${jdk8}/bin", "JAVA_HOME=${jdk8}"]) {
        bat 'mvn -v'
      }
    }
  }
},
"ubuntu-22-amd64-maven-11": {
  stage('Test specific "ubuntu-22-amd64-maven-11" agent label') {
    node('ubuntu-22-amd64-maven-11') {
      sh 'java -version'
      sh 'mvn -v'
    }
  }
},
"ubuntu-22-amd64-maven-17": {
  stage('Test specific "ubuntu-22-amd64-maven-17" agent label') {
    node('ubuntu-22-amd64-maven-17') {
      sh 'java -version'
      sh 'mvn -v'
    }
  }
},
"ubuntu-22-amd64-maven-21": {
  stage('Test specific "ubuntu-22-amd64-maven-21" agent label') {
    node('ubuntu-22-amd64-maven-21') {
      sh 'java -version'
      sh 'mvn -v'
    }
  }
},
"win-2019-amd64-maven-11": {
  stage('Test specific "win-2019-amd64-maven-11" agent label') {
    node('win-2019-amd64-maven-11') {
      bat 'java -version'
      bat 'mvn -v'
    }
  }
},
"win-2019-amd64-maven-17": {
  stage('Test specific "win-2019-amd64-maven-17" agent label') {
    node('win-2019-amd64-maven-17') {
      bat 'java -version'
      bat 'mvn -v'
    }
  }
},
"win-2019-amd64-maven-21": {
  stage('Test specific "win-2019-amd64-maven-21" agent label') {
    node('win-2019-amd64-maven-21') {
      bat 'java -version'
      bat 'mvn -v'
    }
  }
},
"win-2025-amd64-maven-25": {
  stage('Test specific "win-2025-amd64-maven-25" agent label') {
    node('win-2025-amd64-maven-25') {
      bat 'java -version'
      bat 'mvn -v'
    }
  }
}
